### ISSUE TITLE
GraphApiVersion should be easier to modify

### ISSUE THREAD

**Issue by simeyla** [developer82/FacebookCore#2]
You've got GraphApiVersion="v2.8" hardcoded right now, which will expire in a few months.

An overload to FacebookClient(...) which takes an API version would be very useful.

**Comment by developer82** [comment]
Hi,
New refactored code uploaded, which now defaults to v3.2 of the Facebook API.
It can be modified by altering the `GraphApiVersion` property of the `FacebookClient` instance.
